services:
  plantuml:
    image: 'bitjourney/plantuml-service:1.3.5'

  gitbook:
    image: hero/gitbook:1.0.0
    volumes:
      - ./docs:/gitbook
      - plugins:/gitbook/node_modules
    ports:
      - 4000:4000
      - 35729:35729
    depends_on:
      - plantuml
    command: 'serve'

volumes:
  plugins: