FROM ghcr.io/htwg-syslab/container/pythonlab:latest

# C Lab Programming Packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential make gcc clang cmake valgrind \
    libc6-dev gettext indent bats \
    netcat-openbsd net-tools iputils-ping traceroute bmon \
    lsof psmisc \
    xz-utils

# Set clang as gcc
RUN echo "alias gcc='clang'" >> /etc/bash.bashrc