FROM ghcr.io/htwg-syslab/container/bsys-python:latest

# C Programming Packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential gcc clang cmake valgrind \
    netcat-openbsd indent bats \
    gettext

# Set clang as gcc
echo "alias gcc='clang'" >> /etc/bash.bashrc