name: Build Minimal Python Docker Image

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: BsysV2/0Minimal/
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/minimal-python:latest