name: Build Base Docker Image

on:
  push:
    paths:
      - '.github/workflows/1_base.yml'
      - 'BsysV2/1Base/**'
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  REGISTRY: ghcr.io
  IMAGE_TYPE: base

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: BsysV2/1Base/
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_TYPE }}:latest_${{ runner.arch }}

  merge-arches:
    name: Merge Docker Images
    runs-on: ubuntu-latest

    needs:
      - docker-build

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest and push
        run: |
          docker manifest create \
          ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_TYPE }}:latest \
          --amend ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_TYPE }}:latest_X64 \
          --amend ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_TYPE }}:latest_ARM64 && \
          docker manifest push ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_TYPE }}:latest