name: Build UI Docker Image

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build UI Docker Image
        run: docker build BsysV2/2UI/
